### ISSUE TITLE
Issue with class object in PtcDebug.php

### ISSUE THREAD

**Issue by rkpisanu** [ifsale/PhpToolCase#4]
Hi,

In PtcDebug.php there is an error in a line of code 1166.
I resolve with this, comment some lines and changes condition in if statement as below:

					//$rf = @new \ReflectionFunction( $avar );	
					//if ( ( @$rf->getName( ) == '{closure}' ) ) // work with lambda functions first
					if ( false ) // work with lambda functions first

I am not an expert but I think ReflectionFunction doesn't work well with a class.

**Comment by ifsale** [comment]
HI there,

what is the actual error message ?

That part of the code allows to debug objects.
